<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubCategory1_leftmenu_CLP</name>
   <tag></tag>
   <elementGuidId>e4465efd-79fd-401c-b96e-76c3e6089e67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@class='nav-sub-link-leftMenu'][1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>5bf9affa-1c48-4b9c-a253-91816d43c2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1678034253514</value>
      <webElementGuid>4b46529a-e478-4060-9c23-5cfe3871d897</webElementGuid>
   </webElementProperties>
</WebElementEntity>
