<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubCategory2_leftmenu_CLP</name>
   <tag></tag>
   <elementGuidId>a346897c-0f51-4528-95da-5371955d0188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@class='nav-sub-link-leftMenu'][2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>3600a123-2ecf-4623-8de9-40335a1d5540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1678034367066</value>
      <webElementGuid>2207f141-4b9c-4d92-a34e-be28f61fba2f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
