<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Conoce_Mas_sobre_ComplementaryServices_MoreOption_PDP</name>
   <tag></tag>
   <elementGuidId>58618da8-7c58-4e76-a8e3-57afcf77dc0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='ComplementoryServiceCard__body__LearnMore'])</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
