<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProductID_pdp</name>
   <tag></tag>
   <elementGuidId>78afc4a4-da9e-4cba-8685-cd9ec9fa9c11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//p[@class='m-product__information--code'])</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.m-product__information--code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>cb7a3174-38fb-4716-a21b-92f0cc25d9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-product__information--code</value>
      <webElementGuid>87d580ae-d96f-4056-ae92-1e22e0a21063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Código de Producto: 1113670114</value>
      <webElementGuid>22fd1418-0f45-4100-9db5-f472b77fb11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/section[@class=&quot;o-product__detail&quot;]/div[@class=&quot;container o-product__mainContainer&quot;]/main[1]/div[@class=&quot;o-product__description&quot;]/p[@class=&quot;m-product__information--code&quot;]</value>
      <webElementGuid>ccfe70bd-a908-43ab-8434-fbefad785fff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/main/div[2]/p</value>
      <webElementGuid>2676cb6c-c72f-4006-900b-bdbcbbcc0077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lentes de sol Perry Ellis Pesun21015 unisex'])[2]/following::p[1]</value>
      <webElementGuid>b58c3ad2-6842-4c37-b0e7-00effae95c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solares'])[1]/following::p[1]</value>
      <webElementGuid>b1a0c2bd-72b1-4c35-9fa4-2e48d13f8bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Escribe una opinión'])[1]/preceding::p[1]</value>
      <webElementGuid>b9cf9d78-99b1-43a8-b8ed-56f2d2dbfe27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver disponibilidad en tienda'])[1]/preceding::p[1]</value>
      <webElementGuid>8d4655d9-791f-4aec-a146-357ec3fbb384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Código de Producto:']/parent::*</value>
      <webElementGuid>9fc5d027-7bbe-46a4-ae0d-beb4c14fac97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>74136a76-3f25-4fcb-b5a3-2b66647a5fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Código de Producto: 1113670114' or . = 'Código de Producto: 1113670114')]</value>
      <webElementGuid>c7c87e15-cc0a-4c9e-802f-15e5cf5407e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
