<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>breadCrumb_SLP</name>
   <tag></tag>
   <elementGuidId>ea8bf5be-4632-4c87-a510-caac201cbb78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.a-breadcrumb__label.6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='m-breadcrumb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8e055ea7-a7f5-4479-929f-873d92a9e197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-breadcrumb__label 6</value>
      <webElementGuid>b155b51b-9dda-4212-9185-903ab71b4563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tienda?s=regalu#!</value>
      <webElementGuid>75692df9-1f6c-433b-8da8-d4f81468e038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>regalu</value>
      <webElementGuid>42425483-6bab-49b7-9fb8-d5bb0f9e127d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[@class=&quot;container-fluid o-main-container p-0 o-plp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary search---&quot;]/div[@class=&quot;row d-none d-lg-block m-row-bootstrap&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row p-0&quot;]/div[@class=&quot;m-breadcrumb&quot;]/ul[@class=&quot;m-breadcrumb-list&quot;]/li[@class=&quot;active&quot;]/a[@class=&quot;a-breadcrumb__label 6&quot;]</value>
      <webElementGuid>951aceef-a175-436b-b530-8eb7d9439d0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[3]/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>f0bd6c14-2495-47ac-92fc-eda2f43eaff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'regalu')]</value>
      <webElementGuid>5a22e978-71fa-4c82-94c6-f3720c02245f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>e18e3895-8500-4bba-a668-cf496671e2e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtrar'])[1]/following::a[2]</value>
      <webElementGuid>94a9ff2a-ade1-47bf-8c12-576861838890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tal vez quisiste decir'])[1]/preceding::a[1]</value>
      <webElementGuid>1eda971b-4e3a-4b91-9d68-92ff6efcbb6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='regalu']/parent::*</value>
      <webElementGuid>b8ca81a0-db8c-444e-b8ee-725081525331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/tienda?s=regalu#!')])[4]</value>
      <webElementGuid>3e98ace8-65ea-4037-847d-4cc89978a0dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>56609e67-5a0d-4390-b996-b0b8bf8f174f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tienda?s=regalu#!' and (text() = 'regalu' or . = 'regalu')]</value>
      <webElementGuid>7bd8d451-5be8-4cea-97ec-63c0bbdd932b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
