<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubmitButton_LP</name>
   <tag></tag>
   <elementGuidId>5af8f420-791d-44eb-b8b0-e77dfa6bb900</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginFormSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginFormSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c510c047-dc5d-4260-a78b-4c218a5890ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>/atg/agent/userprofiling/AgentProfileFormHandler.login</value>
      <webElementGuid>65c7b366-adb5-4a29-b4b0-6c680a02f98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginFormSubmit</value>
      <webElementGuid>c9e5ceed-5397-46b4-b138-95f09147f567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>509a9dae-027d-41c3-9280-8e07b55689dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Conectar</value>
      <webElementGuid>de600a9f-2496-4ba0-b5da-0d4374f5c271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonSmall go</value>
      <webElementGuid>aae4df6b-e196-43f2-9a9e-8aebaa5eb3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginFormSubmit&quot;)</value>
      <webElementGuid>d7831bc4-f851-49b3-9749-4ace11a0e523</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginFormSubmit']</value>
      <webElementGuid>a23d0016-e976-47ff-a41a-a52929477d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/fieldset/div/input</value>
      <webElementGuid>db6bead3-bcd9-42c8-bbee-bdc234955618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>28a2374d-4e9d-4ed0-bd05-32b5e3a9a33c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '/atg/agent/userprofiling/AgentProfileFormHandler.login' and @id = 'loginFormSubmit' and @type = 'submit']</value>
      <webElementGuid>bdb5ca30-11f6-48b7-ab60-1d439456f2f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
