<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cerrar sesin</name>
   <tag></tag>
   <elementGuidId>1d92e529-3868-4937-992f-8b5c441ac151</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='5']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#5 > a.a-header__sessionLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9abedfb1-ae51-4bae-9e70-5d177e119d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-header__sessionLink</value>
      <webElementGuid>d08cac25-7d9a-4f71-a58b-d003b1d6b7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tienda/home#!</value>
      <webElementGuid>975901b8-e8d2-4d2e-b47c-59e17f7fa7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cerrar sesión</value>
      <webElementGuid>02f1a75e-c94e-49fb-82bc-817681486463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5&quot;)/a[@class=&quot;a-header__sessionLink&quot;]</value>
      <webElementGuid>aa927b40-aa7e-46fb-a3ce-96a58da0e486</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='5']/a</value>
      <webElementGuid>3aa7a112-2062-4f1d-9958-5a4d5c753241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cerrar sesión')]</value>
      <webElementGuid>b39ad86a-546e-42e8-bb42-4519cefcd94c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis tarjetas'])[1]/following::a[1]</value>
      <webElementGuid>eb5ffa46-6a2d-47c0-8650-d0b1465c2851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mi tiempo aire'])[1]/following::a[2]</value>
      <webElementGuid>83b088ed-2bc8-4c40-b0b4-d96c6e05d2f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mi Cuenta'])[2]/preceding::a[1]</value>
      <webElementGuid>0eea8f72-2507-4aa5-b3bc-774570d8fc45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis Compras'])[3]/preceding::a[2]</value>
      <webElementGuid>95358372-241f-455a-89ab-f0845ebed816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cerrar sesión']/parent::*</value>
      <webElementGuid>3e63e34f-acb3-41d4-8044-d54efdc86d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/tienda/home#!')])[4]</value>
      <webElementGuid>848c04f8-f39b-4187-85c4-2f8c69a67914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>dfdfb8a7-70f8-4dfc-8dd8-fff3a7b07241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tienda/home#!' and (text() = 'Cerrar sesión' or . = 'Cerrar sesión')]</value>
      <webElementGuid>43409506-c5c0-40a1-9b91-c5aec511e8a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
