<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mis Compras</name>
   <tag></tag>
   <elementGuidId>fa42ebed-c30d-4fb1-8fd4-397a84b47705</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='1']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1 > a.a-header__sessionLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>138f0b24-031c-4baa-81fb-2d2a279e6baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-header__sessionLink</value>
      <webElementGuid>db2c98bc-1d01-44f0-9d9b-26e00889838f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tienda/users/miscompras</value>
      <webElementGuid>3c23532e-0806-46f0-ac07-5ece47120b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mis Compras</value>
      <webElementGuid>82be293f-65c7-4c6f-aa68-2fb9c6536ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1&quot;)/a[@class=&quot;a-header__sessionLink&quot;]</value>
      <webElementGuid>5b494c62-c164-4a21-bc2c-209041e22cdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='1']/a</value>
      <webElementGuid>c9fc4631-d18e-459d-a4a9-39e5bd1f0a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Mis Compras')])[2]</value>
      <webElementGuid>7fa50cf5-e200-4a86-9a79-437a31447908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mi Cuenta'])[1]/following::a[1]</value>
      <webElementGuid>832e2f7e-393c-49c5-b0ee-e2c4d7449a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hola SAMRAJ'])[1]/following::a[2]</value>
      <webElementGuid>636cf7f7-6d63-4c2c-ac06-8a6a7426d4bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cupones'])[1]/preceding::a[1]</value>
      <webElementGuid>03d21f86-af02-4271-b352-5aa045fc3156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mi tiempo aire'])[1]/preceding::a[2]</value>
      <webElementGuid>70a05906-ff17-458c-a75f-7e77c2e9fda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/tienda/users/miscompras')]</value>
      <webElementGuid>99e09aab-1b2f-4ac7-8244-4be2e6960807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>66812688-275b-4be7-92cc-ef53771fb884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tienda/users/miscompras' and (text() = 'Mis Compras' or . = 'Mis Compras')]</value>
      <webElementGuid>4fef0e93-6b5e-419c-9367-6a39cf358a95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
