<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Crear cuenta</name>
   <tag></tag>
   <elementGuidId>b223ec2e-dcae-4511-8d00-0e716cff90e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='action']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;action&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>02182cc5-f930-4a25-8671-f2dec8c0b6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a8046578-10d6-4ff6-8750-0b48efd7836b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>94ffc39d-eee9-4fde-8680-76e3f6c494a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>cf0b7dd6-f50d-4895-ae99-5b704b95e9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c818c634d cab70d39b c9fec752d c570086c6 c696779d3</value>
      <webElementGuid>b48a0481-bd8c-411a-b6d4-edeba7c4f3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Crear cuenta</value>
      <webElementGuid>4d1caa56-3e42-4970-894a-bb3add2cf746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;_widget-auto-layout _hide-prompt-logo&quot;]/main[@class=&quot;_widget c9d5d442b&quot;]/section[@class=&quot;c816e925e _prompt-box-outer cfabdf962&quot;]/div[@class=&quot;c41b10a9e c5d6300a1&quot;]/div[@class=&quot;c37260841&quot;]/div[@class=&quot;cd2091297 c66a28951&quot;]/form[@class=&quot;c343a2ca4 c15ff9a9f&quot;]/div[@class=&quot;c93926433&quot;]/button[@class=&quot;c818c634d cab70d39b c9fec752d c570086c6 c696779d3&quot;]</value>
      <webElementGuid>23afeea3-9e18-4519-949e-23fcd555af9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='action']</value>
      <webElementGuid>0c6afad5-c00a-40be-9968-e44b7ab3d52b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Números (0-9)'])[1]/following::button[1]</value>
      <webElementGuid>30ea855a-408d-42d1-a4a5-04386b7435e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Letras mayúsculas (A-Z)'])[1]/following::button[1]</value>
      <webElementGuid>c4905bd4-c3b7-4934-b4e4-0bd14afb6c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicia sesión'])[1]/preceding::button[1]</value>
      <webElementGuid>4919a67d-5a4d-464f-a9c6-9c87182c1f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[1]/preceding::button[1]</value>
      <webElementGuid>2c598f23-85f3-4745-b47e-11ceaba090eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>36322553-dc71-43b8-ad0e-952269b915ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'action' and (text() = 'Crear cuenta' or . = 'Crear cuenta')]</value>
      <webElementGuid>74e1edfa-7d77-4b90-bf6c-cb55d75ec424</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
