<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ClickNCollectionAddressTitle_Account</name>
   <tag></tag>
   <elementGuidId>06419b20-2212-470c-a317-04eafbf92130</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//h1[@class='a-cards__titleCard'])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
