<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_day_AM</name>
   <tag></tag>
   <elementGuidId>284b7a1f-67f1-45be-af40-d0ad0652da8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='daySelectorLabel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#daySelectorLabel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fc21c0e0-5ee1-4deb-9734-6c38b23a4377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-select__native-control</value>
      <webElementGuid>5da599ca-3344-439c-b79f-e25e5855b526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>daySelectorLabel</value>
      <webElementGuid>f4ae2f50-fa92-4cce-b89e-9110155ec905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12345678910111213141516171819202122232425262728293031</value>
      <webElementGuid>54208163-195a-411f-83a5-38c1d0bc383f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formCreateAccount&quot;)/div[@class=&quot;row m-wrapDate mt-3&quot;]/div[@class=&quot;col-4 firstDatePicker select-datePicker-space&quot;]/div[@class=&quot;mdc-ripple-upgraded mdc-select--focused mdc-ripple-upgraded--background-focused&quot;]/div[@class=&quot;mdc-select mdc-select--outlined mdc-select--focused&quot;]/select[@id=&quot;daySelectorLabel&quot;]</value>
      <webElementGuid>08c0936c-7f6f-4f15-9e52-42d30e0ed6d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='daySelectorLabel']</value>
      <webElementGuid>98b4f710-7159-456a-b63b-5516605c44f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formCreateAccount']/div[9]/div/div/div/select</value>
      <webElementGuid>878aaf8f-a958-493a-8d9f-2bb7cd18cd0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de Nacimiento'])[1]/following::select[1]</value>
      <webElementGuid>a26acee0-f78c-438f-ac24-52c6737f7a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apellido Materno'])[1]/following::select[1]</value>
      <webElementGuid>f90aebb1-d4bf-4ff9-9d48-dd53a90c8ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Día'])[1]/preceding::select[1]</value>
      <webElementGuid>217a4db4-de9b-4c8e-9835-efa9140fe2d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mes'])[1]/preceding::select[2]</value>
      <webElementGuid>ceba6299-b524-4994-8b7e-132c691b73d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f64d9e55-b1fc-4456-a05e-509e8f378221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'daySelectorLabel' and (text() = '12345678910111213141516171819202122232425262728293031' or . = '12345678910111213141516171819202122232425262728293031')]</value>
      <webElementGuid>c5cdfa63-845c-4140-968a-d7a908207679</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
