<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_month_AM</name>
   <tag></tag>
   <elementGuidId>96743ba9-e375-412a-b9fc-5157a55064bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='monthSelectorLabel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#monthSelectorLabel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b7a815f8-f44f-43ed-8625-9863b63ebfbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-select__native-control</value>
      <webElementGuid>e88e77e0-65cb-4561-b60a-1d0ad3028cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>monthSelectorLabel</value>
      <webElementGuid>b4541d64-fbe9-4795-8369-fdbfe22ce2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EneFebMarAbrMayJunJulAgoSepOctNovDic</value>
      <webElementGuid>b7ff2823-0be0-4b76-ba15-929d80b75288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formCreateAccount&quot;)/div[@class=&quot;row m-wrapDate mt-3&quot;]/div[@class=&quot;col-4 middleDatePicker select-datePicker-space&quot;]/div[@class=&quot;mdc-ripple-upgraded mdc-select--focused mdc-ripple-upgraded--background-focused&quot;]/div[@class=&quot;mdc-select mdc-select--outlined mdc-select--focused&quot;]/select[@id=&quot;monthSelectorLabel&quot;]</value>
      <webElementGuid>2320dcc2-3901-4341-a23c-a3722c4f0e7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='monthSelectorLabel']</value>
      <webElementGuid>3513c291-2bc2-4b36-9aaf-3ace8f6c8f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formCreateAccount']/div[9]/div[2]/div/div/select</value>
      <webElementGuid>57bf2e36-d6ab-4f82-9113-e52820a35075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Día'])[1]/following::select[1]</value>
      <webElementGuid>73553a49-9556-4631-97e9-9ee770e2c570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de Nacimiento'])[1]/following::select[2]</value>
      <webElementGuid>a417dfb2-f9db-40aa-863b-cb81b14c8367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mes'])[1]/preceding::select[1]</value>
      <webElementGuid>03e19c98-a9f4-4c14-8334-40fb2d996b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Año'])[1]/preceding::select[2]</value>
      <webElementGuid>f9728c13-655b-4229-aa05-f160d0dc7f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>8756c208-6faa-4f47-9b97-0a8dd42ce9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'monthSelectorLabel' and (text() = 'EneFebMarAbrMayJunJulAgoSepOctNovDic' or . = 'EneFebMarAbrMayJunJulAgoSepOctNovDic')]</value>
      <webElementGuid>c622981b-ff0f-48ca-9e2e-88b773172bf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
