<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>breadCrumb_misCompras</name>
   <tag></tag>
   <elementGuidId>9f36b965-0782-4f4e-b0c9-d2b5b57cb10b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.m-breadcrumb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = '  Home   Mi Cuenta   Mis Compras ' or . = '  Home   Mi Cuenta   Mis Compras ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>12319352-d12a-4082-ae06-b07039557db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-breadcrumb</value>
      <webElementGuid>ea695df5-3004-4257-8f7f-f15c0551497c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Home   Mi Cuenta   Mis Compras </value>
      <webElementGuid>74a50102-e494-4aa0-a8c8-1aa56feb16c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;container-fluid o-main-container p-0&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row d-none d-lg-block m-row-bootstrap&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row p-0&quot;]/div[@class=&quot;m-breadcrumb&quot;]</value>
      <webElementGuid>2cdd2ba7-1ac5-46d0-9b20-7f31943df7f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/div</value>
      <webElementGuid>1dc4b412-da26-488f-a03b-d8b925b1c0f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liverpool Polanco'])[2]/following::div[11]</value>
      <webElementGuid>96389459-06cf-4ea0-80b5-623ae3395a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mi tienda'])[2]/following::div[11]</value>
      <webElementGuid>0a3bce96-435a-4359-bd7a-33a7292c472a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div</value>
      <webElementGuid>c223ad29-21d7-4fdf-a2f4-7fbfee2a1013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '  Home   Mi Cuenta   Mis Compras ' or . = '  Home   Mi Cuenta   Mis Compras ')]</value>
      <webElementGuid>3468d6a2-0429-4993-a013-e7ae29029797</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
