<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_product__image_misCompras</name>
   <tag></tag>
   <elementGuidId>7f7ba8ad-6dbc-4caf-bc96-8c921699ea0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-xs-2.col-sm-3.col-md-3.col-lg-3.MisComprasProductImage > figure.MisCompImgWidth.MisCompProdImgWidth > img.a-order__product__image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='col-xs-2 col-sm-3 col-md-3 col-lg-3 MisComprasProductImage'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9c0ded9e-6f98-418c-9326-326fa5f8c9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>44931d75-1ef8-44bb-8ef0-79fb9733688a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss237.liverpool.com.mx/sm/1111964187.jpg</value>
      <webElementGuid>367338fd-10a9-4ea0-9380-7323cbfd9062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ZAPATO DOCKERS D2122, 28 CM, CHOCOLATE</value>
      <webElementGuid>803643c8-f8be-45f5-ab2d-c0deac4a236d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-order__product__image</value>
      <webElementGuid>9133ed95-456b-4e5e-b4fa-42399d94a4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;container-fluid o-main-container p-0&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/div[@class=&quot;col-lg-9 m-column_mainContent&quot;]/div[@class=&quot;MisComprasContainer d-none d-lg-block desktop&quot;]/div[3]/div[@class=&quot;col-xs-2 col-sm-3 col-md-3 col-lg-3 MisComprasProductImage&quot;]/figure[@class=&quot;MisCompImgWidth MisCompProdImgWidth&quot;]/img[@class=&quot;a-order__product__image&quot;]</value>
      <webElementGuid>69df82fe-13a7-4f70-870a-90b73d256d7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[3]/div[2]/div[4]/div[3]/div/figure/img</value>
      <webElementGuid>4ad641f4-cf11-4012-8678-76fdd51c883c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='ZAPATO DOCKERS D2122, 28 CM, CHOCOLATE'])[2]</value>
      <webElementGuid>36fc72fb-a340-4d12-bb87-e4a884daa011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/figure/img</value>
      <webElementGuid>211527fb-de0d-4dad-9ccc-0e84a457144a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ss237.liverpool.com.mx/sm/1111964187.jpg' and @alt = 'ZAPATO DOCKERS D2122, 28 CM, CHOCOLATE']</value>
      <webElementGuid>b852ce96-cee8-45f8-b0ae-a38ed2bf795e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
