<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ayuda_footer</name>
   <tag></tag>
   <elementGuidId>0ab53d2a-ad94-485a-aebc-a9b100f8f6e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='#collapseSupport']/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed0142f8-f7f0-4c69-9ec7-23e1e472c642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-footer__link</value>
      <webElementGuid>48d806c8-9eab-434e-a34a-22c4b9110918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://assetspwaqa.liverpool.com.mx/ayuda/index.html?_ga=2.60689709.1844689030.1668394648-1856063147.1668394648#/</value>
      <webElementGuid>0cee475e-3770-4419-9738-71edd9b9d24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ayuda</value>
      <webElementGuid>f2d75592-a53c-48bd-a6a3-a62c5d544bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;#collapseSupport&quot;)/div[@class=&quot;card-body pt-0 pb-lg-0&quot;]/ul[@class=&quot;m-0&quot;]/li[@class=&quot;p-0&quot;]/a[@class=&quot;a-footer__link&quot;]</value>
      <webElementGuid>036a403a-15d4-4cbb-95a5-499508ddf2bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='#collapseSupport']/div/ul/li[2]/a</value>
      <webElementGuid>a893b4a8-45ec-418f-99d1-2493afdcc532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Ayuda')])[2]</value>
      <webElementGuid>6b4c28a4-4b35-4a89-ad71-124abbc9eb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facturación'])[1]/following::a[1]</value>
      <webElementGuid>b1104f6d-0a79-48c8-8400-6896c8dcb92d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soporte al cliente'])[1]/following::a[2]</value>
      <webElementGuid>1dd4333f-1fa9-4b82-83bc-b9c64c452a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis Compras'])[2]/preceding::a[1]</value>
      <webElementGuid>40f3a067-1602-4e93-aa08-091222690687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Garantía Liverpool'])[1]/preceding::a[2]</value>
      <webElementGuid>90aa8567-e3ab-4783-8228-8218027aecac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://assetspwaqa.liverpool.com.mx/ayuda/index.html?_ga=2.60689709.1844689030.1668394648-1856063147.1668394648#/')]</value>
      <webElementGuid>c0fff40e-3f33-4f07-a2f2-465a1757b163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/div/div/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>2a7178db-987c-4089-bdda-f1b274c30310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://assetspwaqa.liverpool.com.mx/ayuda/index.html?_ga=2.60689709.1844689030.1668394648-1856063147.1668394648#/' and (text() = 'Ayuda' or . = 'Ayuda')]</value>
      <webElementGuid>054fe052-d6fe-438f-8d5c-99915c9e0f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
