<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CategorasDropDown_HP</name>
   <tag></tag>
   <elementGuidId>ffa72da8-54b0-40aa-a5bd-b12d6b9201ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon-arrow_down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='a-header__strongLink nav-desktop-menu-action pr-3 pb-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f3a528aa-8bc2-4bd0-92b6-cbc1ecfcd870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-arrow_down</value>
      <webElementGuid>9ff528c0-cf19-4f0f-87ab-c03e7334908e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/header[1]/div[@class=&quot;o-header&quot;]/div[@class=&quot;o-container__fluid container-fluid wrap-megamenu d-none d-lg-block&quot;]/div[@class=&quot;o-container container p-0&quot;]/nav[@class=&quot;m-megamenu&quot;]/div[@class=&quot;o-row row align-items-center&quot;]/div[@class=&quot;o-col col-lg-10 col-xl-9 pr-0&quot;]/div[@class=&quot;o-row row&quot;]/div[@class=&quot;o-col col-lg-auto col-6 order-lg-1 text-center&quot;]/div[@class=&quot;o-navDesktop&quot;]/ul[@class=&quot;m-navDesktop__menuList&quot;]/li[@class=&quot;m-navDesktop__section pt-2 pb-2 mr-xl-5&quot;]/span[@class=&quot;a-header__strongLink nav-desktop-menu-action pr-3 pb-3 m-megamenu_dropdown_show&quot;]/i[@class=&quot;icon-arrow_down&quot;]</value>
      <webElementGuid>ea76efab-1e1d-401b-99ce-b49f79e442b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/header/div[4]/div[3]/div/nav/div/div/div/div/div/ul/li/span/i</value>
      <webElementGuid>0a0dfea0-b20e-45aa-82f1-889b06dbf401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/i</value>
      <webElementGuid>8b7d8886-78be-44b1-ab15-dce3db1b231b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
