<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Cmo podemos ayudarte_logoAyuda_helpPage</name>
   <tag></tag>
   <elementGuidId>29ae5d4a-5359-4ec0-93e1-e076506dece0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.logoAyuda</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainContent']/div/header-web/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e4535b16-61b1-4541-8c84-4a12696a0108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logoAyuda</value>
      <webElementGuid>7e3e954e-44b8-4d64-9e18-5e57749770aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/logoAyuda.png</value>
      <webElementGuid>d702a662-c945-42b0-8580-b649b9797f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Ayuda Liverpool logo</value>
      <webElementGuid>01ba2fd4-e100-4370-8524-8c0b3ca70b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;grid-container ng-scope&quot;]/header-web[1]/div[@class=&quot;grid-80 prefix-10 sufix-10 header-ayuda&quot;]/div[@class=&quot;logaA&quot;]/a[1]/img[@class=&quot;logoAyuda&quot;]</value>
      <webElementGuid>46269288-e0d2-45df-b4a1-66b9bac4b3b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/header-web/div/div/a/img</value>
      <webElementGuid>dd86cbfb-f47e-44b8-94ea-45bec4b91775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Ayuda Liverpool logo']</value>
      <webElementGuid>1171c073-0082-41ad-a041-ad2b7a49e932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>9bccd0e5-5e61-4557-b7e3-6665e0ae2191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/logoAyuda.png' and @alt = 'Ayuda Liverpool logo']</value>
      <webElementGuid>dc29cf27-3463-45da-979f-6aeacc12af1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
