<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Logo_hp</name>
   <tag></tag>
   <elementGuidId>5097d239-d080-4218-b9a3-de93d468e34c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a/img)[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.a-header__logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0eb6fcc3-834c-4e30-998c-fafc3329d7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assetspwa.liverpool.com.mx/assets/images/logos/liverpool-logo.svg</value>
      <webElementGuid>916eb1bb-68ef-436e-81a7-5d3f9d5bd82f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-header__logo</value>
      <webElementGuid>027accef-e599-4038-a2a9-437c70ac0541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Liverpool Logo</value>
      <webElementGuid>36262ae6-ad2d-4dfd-ab0c-e1bb3e120c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Liverpool Logo</value>
      <webElementGuid>f322458e-f0fc-4ebb-aaba-b523285bce9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/header[1]/div[@class=&quot;o-header&quot;]/div[@class=&quot;o-container__fluid container-fluid&quot;]/div[@class=&quot;o-container container p-0&quot;]/div[@class=&quot;m-searchBar&quot;]/div[@class=&quot;o-checkout__header o-row row align-items-center no-gutters py-3 py-lg-2&quot;]/div[@class=&quot;o-col col-lg-auto col-6 order-2 order-lg-1 text-center min-width-logo&quot;]/a[1]/img[@class=&quot;a-header__logo&quot;]</value>
      <webElementGuid>2ff47cc1-9e51-47c9-8c4d-b1fcac9ec942</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/header/div[4]/div[2]/div/div/div/div[2]/a/img</value>
      <webElementGuid>3e50adc3-e180-4c85-8d9f-0c1e68ee586e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Liverpool Logo']</value>
      <webElementGuid>270e2688-ac29-4058-a8fa-bcfe8fe1e82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>1c3b0102-9502-469a-b61a-b328c77cfef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assetspwa.liverpool.com.mx/assets/images/logos/liverpool-logo.svg' and @alt = 'Liverpool Logo' and @title = 'Liverpool Logo']</value>
      <webElementGuid>1cc61d11-900f-4ee3-99ae-9c50dffae3ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
