<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Mesa de regalos_HP</name>
   <tag></tag>
   <elementGuidId>1f198f61-8690-4ad0-be39-7f84b08546f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.a-header__strongLink.m-ipadLeftLink.pr-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/header/div[4]/div[3]/div/nav/div/div/div/div[2]/div/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6a2d14da-4d4b-4d08-9b58-df92e0865423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-header__strongLink m-ipadLeftLink pr-4</value>
      <webElementGuid>3dfe30fe-1dc7-4701-b5f8-98d6b3147f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://mesaderegalosqa.liverpool.com.mx/?_ga=2.60660141.1296604941.1668303679-90015236.1668303679</value>
      <webElementGuid>b49cdeca-6c3e-414e-bf63-fac71c0b1fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mesa de regalos</value>
      <webElementGuid>3691849d-e369-49a6-bec9-f630c7c539e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/header[1]/div[@class=&quot;o-header&quot;]/div[@class=&quot;o-container__fluid container-fluid wrap-megamenu d-none d-lg-block&quot;]/div[@class=&quot;o-container container p-0&quot;]/nav[@class=&quot;m-megamenu&quot;]/div[@class=&quot;o-row row align-items-center&quot;]/div[@class=&quot;o-col col-lg-10 col-xl-9 pr-0&quot;]/div[@class=&quot;o-row row&quot;]/div[@class=&quot;o-col col-lg order-lg-2 pt-3 pt-lg-0&quot;]/div[@class=&quot;o-row row&quot;]/div[@class=&quot;o-col px-0 text-left col-lg-5 col-xl-6&quot;]/ul[@class=&quot;m-navDesktop__menuList&quot;]/li[@class=&quot;m-navDesktop__section pt-2 pb-2&quot;]/a[@class=&quot;a-header__strongLink m-ipadLeftLink pr-4&quot;]</value>
      <webElementGuid>ffd319d4-dd8f-4d0b-857c-3201cda55ad5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/header/div[4]/div[3]/div/nav/div/div/div/div[2]/div/div/ul/li/a</value>
      <webElementGuid>73a59393-7a79-4710-8b0a-e22a22848fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mesa de regalos')]</value>
      <webElementGuid>42708313-c12c-4799-beca-1b40518a1d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Niños'])[4]/following::a[1]</value>
      <webElementGuid>1d448892-523c-43bd-9241-129ca1c6f0d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bebés'])[4]/following::a[2]</value>
      <webElementGuid>01bacbed-5c82-4e36-bbf7-4950cfdce57f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mi crédito'])[1]/preceding::a[1]</value>
      <webElementGuid>aea1514f-6770-4ffd-bd69-a863b3e8b0a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Centro de seguros'])[1]/preceding::a[2]</value>
      <webElementGuid>e77cd7de-24c9-4f28-b2f7-5d84dffa8d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mesa de regalos']/parent::*</value>
      <webElementGuid>34cc8c72-c382-4225-8cf5-b21ba1a1ce47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://mesaderegalosqa.liverpool.com.mx/?_ga=2.60660141.1296604941.1668303679-90015236.1668303679')]</value>
      <webElementGuid>c5a5b616-b69d-4df3-925f-93ffa598d379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li/a</value>
      <webElementGuid>b3f108c5-66ad-4e13-8818-dcf861c2e4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://mesaderegalosqa.liverpool.com.mx/?_ga=2.60660141.1296604941.1668303679-90015236.1668303679' and (text() = 'Mesa de regalos' or . = 'Mesa de regalos')]</value>
      <webElementGuid>f1b6b1ef-b8e2-4b11-8182-3f4daca6e973</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
