<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Seach_TextBox_hp</name>
   <tag></tag>
   <elementGuidId>cfa8f443-f074-4dd7-988d-2649cf71f434</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainSearchbar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mainSearchbar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78722cc3-bacc-45fd-bb4e-faa78205bdf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainSearchbar</value>
      <webElementGuid>a7124625-f362-4405-912d-2b3880749ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-bar plp-no__results</value>
      <webElementGuid>e1df18d0-c530-4718-ad00-263ad5fd1bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Buscar ...</value>
      <webElementGuid>5beba1c2-8a45-414d-a235-65347e750950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd3e92c9-3cf0-424d-bf4d-3662ad33e009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buscar...</value>
      <webElementGuid>52861f08-c0ad-4b25-bb4f-c1f298e4c158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f6c00fb3-a2ea-4551-be81-a954c522c226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainSearchbar&quot;)</value>
      <webElementGuid>17b29acb-2a3b-4606-8ec8-1ec1a2703900</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mainSearchbar']</value>
      <webElementGuid>2ad62ea4-31e5-4d0a-b894-6a348ad9f246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/header/div[4]/div[2]/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>227630a6-8af1-41be-892e-46a949caac89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>c7a94865-918d-4612-86f9-149b0a8b4953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mainSearchbar' and @type = 'text' and @placeholder = 'Buscar...']</value>
      <webElementGuid>91d8a516-5177-4096-982a-739fcb41e586</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
