<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ForwardArrow_Pagenation_PLP</name>
   <tag></tag>
   <elementGuidId>99bc1063-dd9e-4c14-8f48-6e225c2b9350</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//li[@class='page-item'])//i[@class='icon-arrow_right']/..
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
