<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Toys R Us_mainSearchbar</name>
   <tag></tag>
   <elementGuidId>7aca6ea1-f19e-4f64-a2a6-2955f210828f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainSearchbar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mainSearchbar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1caee02-9b51-4952-bb14-0c28913e1f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainSearchbar</value>
      <webElementGuid>43dd0abb-c9df-4f8a-b83d-b7c988f6198f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-bar plp-no__results</value>
      <webElementGuid>4e699334-9b76-4343-b6d6-b7e953112928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Buscar ...</value>
      <webElementGuid>f3acf2ef-cc20-469e-916c-6db1dee67baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74505c8b-5779-4749-b815-725da08febea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buscar...</value>
      <webElementGuid>c3d058ec-58cd-4498-b750-64dfe4181200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>974003d1-c86b-4b7e-aea4-caeb5b6fcb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainSearchbar&quot;)</value>
      <webElementGuid>e42ff504-99ed-45f6-adf2-8f2eded7baf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mainSearchbar']</value>
      <webElementGuid>493f2c2a-728a-4c75-ab49-50fed1d1c3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/header/div[3]/div[2]/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>412aedb4-d25a-445a-a203-fe8c312de3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>d9569422-8aa9-43db-becc-12bbb5bf21e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mainSearchbar' and @type = 'text' and @placeholder = 'Buscar...']</value>
      <webElementGuid>28af3c2f-8990-44c6-9a2d-b41ddc79c916</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
