<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>hgfgh</description>
   <name>product1_PLP</name>
   <tag></tag>
   <elementGuidId>a32efccf-f629-4d6a-b950-237f476e4d6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
