<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchProductName_SP</name>
   <tag></tag>
   <elementGuidId>47d63a59-1e42-43bb-a81f-1e961597c9c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchTermInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchTermInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1aadae8-8663-482b-9487-f21c38400e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36e1c23f-f3e6-4daa-b044-a349ee56fced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-box ui-autocomplete-input</value>
      <webElementGuid>04a7badc-eb91-432e-bec1-8b16ec102396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>88982358-ea21-46f1-a0ac-abf4fa66b3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchTermInput</value>
      <webElementGuid>a89ce087-afaf-4535-b9ae-da97044b3ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>searchTermInputOnkeydown();</value>
      <webElementGuid>8b4bcae4-b63a-487b-989a-bf15acb8d3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>searchTermInputOnkeyup(); if(event.keyCode==13){searchTermInputOnkeydown(); submitSearchTermRequest('/agent/framework.jsp?_windowid=32&amp;ps=cmcCatalogPS&amp;p=cmcProductCatalogSearchP');}</value>
      <webElementGuid>14edf54f-b65a-41d0-a6f4-9617d786fa07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c439796a-3fac-429c-9fb2-6e6e3e12fc65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchTermInput&quot;)</value>
      <webElementGuid>45471d37-99b4-4d16-860b-52c2abbfa53f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchTermInput']</value>
      <webElementGuid>9c9a117c-3ab7-4094-833b-0f55c3a69b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='catalog-nav']/div/ul/li/input</value>
      <webElementGuid>e8d6cf16-0137-441f-80c8-dd905eddabfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>661e9b27-1618-481e-84df-f217da84fe03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Buscar' and @id = 'searchTermInput']</value>
      <webElementGuid>2ce19063-f34b-4fcb-ba34-6dbca807dbaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
