<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continuar</name>
   <tag></tag>
   <elementGuidId>9c862a08-8260-4cae-a7cc-52e84669cf3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loggedInCC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='loggedInCC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>157a0596-21c3-4bfa-b662-4cf36021338d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--primary</value>
      <webElementGuid>9d0e3062-2e28-4abc-96ff-64f721e9a5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loggedInCC</value>
      <webElementGuid>35f2d6fd-136b-441a-9b4a-e5bbde5291bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-condition</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>f8108681-8914-4fc1-87b9-a587385683c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>277e3c0b-81ef-40ef-9a46-76fce99e4e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loggedInCC&quot;)</value>
      <webElementGuid>779f521f-bb08-401c-8ecb-22bbc28ae562</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='loggedInCC']</value>
      <webElementGuid>dff2a4ac-1464-4828-9e24-f1fb499287a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_deliveryPayModalButtons']/div[2]/button</value>
      <webElementGuid>11a4306b-d52d-4ff1-aeaa-daddc7707228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agregar una tarjeta'])[1]/following::button[1]</value>
      <webElementGuid>94b52281-1a59-40f4-ba42-ebeb05726906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[1]/following::button[2]</value>
      <webElementGuid>693c1763-ed8c-4d38-a38e-a2db12f7035d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tienes un cupón disponible en tu bolsa'])[1]/preceding::button[1]</value>
      <webElementGuid>4b2dc88e-3e38-4725-ac0e-9385df891834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver mis cupones'])[1]/preceding::button[1]</value>
      <webElementGuid>3f803835-ab24-40c4-8954-50198e2f6852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continuar']/parent::*</value>
      <webElementGuid>76a5314f-1e92-41ee-9383-f4bc9aa76e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>97383fc8-1104-408b-8081-1552f02f19fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'loggedInCC' and (text() = 'Continuar' or . = 'Continuar')]</value>
      <webElementGuid>1ebf8665-2e1f-484d-b441-82341957b1f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
