<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tarjetas  Monedero_paypalImage</name>
   <tag></tag>
   <elementGuidId>46baf1d8-37af-4fe6-835f-ea5b60cf8886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paypalImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='paypalImage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2712f6bb-fd88-4312-9995-4cc853b20820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../static/images/atomo-icono-paypal.svg</value>
      <webElementGuid>effd5f80-2d67-4bb2-befa-39eb4b32d5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo PayPal</value>
      <webElementGuid>583eecd8-212e-4124-bca7-b29f771c6c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-paymentOptionContainer__logo img-fluid</value>
      <webElementGuid>563a5219-2048-4672-9699-fd3f0fbdf943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paypalImage</value>
      <webElementGuid>fb106b19-9bd1-4482-be8e-ea352f1f1bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paypalImage&quot;)</value>
      <webElementGuid>1c14ad66-556e-4e6f-90ab-ed99522c171a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='paypalImage']</value>
      <webElementGuid>7efece9b-5f48-42ee-a824-b5538bb954d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_modalbody']/div/div[2]/button[2]/img</value>
      <webElementGuid>979d35de-1d89-4e0f-b693-7b68a5eadb59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo PayPal']</value>
      <webElementGuid>12a82b6a-255f-4e46-af0f-5f5e6bc3131a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/img</value>
      <webElementGuid>61502c4b-286c-48e7-83b3-16b1eb0203cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../../static/images/atomo-icono-paypal.svg' and @alt = 'Logo PayPal' and @id = 'paypalImage']</value>
      <webElementGuid>075c55b0-c271-4c73-9a50-4855e471097e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
