<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_text</name>
   <tag></tag>
   <elementGuidId>3e6aa0ea-8125-41c8-be3b-fe1211e64477</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cardExp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cardExp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d3b50f2-3b44-42f4-b259-618d101d0058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardExp</value>
      <webElementGuid>bc5f09c0-7bdc-4b53-ab1d-bb78fc12e18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-textField__input mdc-text-field__input</value>
      <webElementGuid>26af21d1-52e3-44fb-a964-26e833e63d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>3bb995a7-ffda-4d88-8c12-6aa6efbe671d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7ef5cccb-6182-4b00-8b6b-d4d1cbb6d5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>helper-nombreCorto</value>
      <webElementGuid>11a59057-2ca2-4845-8307-a4fd2534fff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>helper-nombreCorto</value>
      <webElementGuid>68527233-1b6e-4e2f-9ff3-6e1205bed558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b40d79a-7717-4764-a779-fda6b401a8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>onlyNumbersWithCharacters</value>
      <webElementGuid>0fcaefd8-430b-457e-b580-316aa4fd6aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ba181f42-f3b7-4b14-867e-24c683e58def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardExp</value>
      <webElementGuid>ee106ba9-74fc-4b11-888c-32609db60863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>reference</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>f98d41e3-bef9-4837-8de0-99576ccc35a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputid</name>
      <type>Main</type>
      <value>cardExp</value>
      <webElementGuid>d1df318c-d200-47d9-86fe-1923ece351ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labeltext</name>
      <type>Main</type>
      <value>MM/AA</value>
      <webElementGuid>855e5deb-259d-478d-9a3c-5b910199e94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelposition</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>eb5be267-5435-48d0-8cad-1e12bbd1dba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>ff34bf7c-f355-4782-add7-be8ecfa73085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e76c1c04-fb3e-46e2-a28b-3ce05ca69d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditCardOrganism&quot;)/label[@class=&quot;o-singleCardInfo -bottomDivider no-gutters align-items-start justify-content-start mb-3&quot;]/div[@class=&quot;col-11 ml-5&quot;]/div[@id=&quot;case1&quot;]/div[1]/div[@class=&quot;d-flex align-items-start justify-content-start col-12 p-0 mt-3 mt-lg-0&quot;]/div[@class=&quot;col-lg-12 col-6 pl-0 col-xl-3&quot;]/div[@class=&quot;m-textField mdc-text-field mdc-text-field--outlined mdc-text-field--valid mdc-text-field--focused&quot;]/input[@id=&quot;cardExp&quot;]</value>
      <webElementGuid>aac3baec-1f98-4ff6-baf8-fb27e9b56c8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cardExp']</value>
      <webElementGuid>748b7a48-436c-42c0-8b39-4fde3c3105ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='case1']/div/div/div/div/input</value>
      <webElementGuid>c37a8b58-f480-4d5b-8898-6dcfa88cf8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/input</value>
      <webElementGuid>fc63d509-3201-4b6c-8469-122ee36761c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cardExp' and @type = 'tel' and (text() = 'text' or . = 'text') and @name = 'cardExp']</value>
      <webElementGuid>17cc0755-2501-400d-8e31-a8941782a941</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
