<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cdigo de seguridad</name>
   <tag></tag>
   <elementGuidId>0ea228e1-c9a4-4ca6-b11c-bd231e4d1a6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cvv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cvv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffadc1e9-e49d-47f7-b84f-cc62c86c7ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cvv</value>
      <webElementGuid>0b6451b4-8581-4da6-a05a-9a0c77f9a29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-textField__input mdc-text-field__input</value>
      <webElementGuid>6ff364e1-f22a-494a-b1b6-d88e8fbe5bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>31ccf4a7-c081-4f9d-9e58-7450c6405bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>35691922-fd4e-45d9-abf3-f7fbf6fe774f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>helper-nombreCorto</value>
      <webElementGuid>63bd0faa-5546-4228-a430-e76791ef807e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>helper-nombreCorto</value>
      <webElementGuid>1ed6ca48-3052-413e-8d53-9cd74f062949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Código de seguridad</value>
      <webElementGuid>d74fdb5e-e9ec-4496-912c-f9abb17a4596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>onlyNumbersWithMaxLength</value>
      <webElementGuid>80c9ce7f-a2fc-4b86-a62d-badec2c4902a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d0c189a1-9600-495a-bde5-24d1fd987fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cvv</value>
      <webElementGuid>fafb8db1-f51e-48f3-b18e-ffa8a97b22d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>reference</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>cc2ea046-c060-4e07-880c-777dafc12399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputid</name>
      <type>Main</type>
      <value>cvv</value>
      <webElementGuid>27a55d27-ecad-464c-9268-0ac3f8e402ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nameinput</name>
      <type>Main</type>
      <value>Código de seguridad</value>
      <webElementGuid>ef9e7b52-ff90-4d4e-96c8-5f950f4442e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labeltext</name>
      <type>Main</type>
      <value>CVV</value>
      <webElementGuid>0db9863f-a6f6-4587-a0eb-a2d69ac13368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelposition</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>0a8987b5-9add-4588-bded-0d34f87ed3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpertextid</name>
      <type>Main</type>
      <value>helper-nombreCorto</value>
      <webElementGuid>e8e0eca3-bbf3-4147-8bff-027c70c928c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>b61a991e-f15b-43db-a7c5-0ce8f23d10e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>118f9940-5384-47bc-887b-91c114699030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditCardOrganism&quot;)/label[@class=&quot;o-singleCardInfo -bottomDivider no-gutters align-items-start justify-content-start mb-3&quot;]/div[@class=&quot;col-11 ml-5&quot;]/div[@id=&quot;case1&quot;]/div[1]/div[@class=&quot;d-flex align-items-start justify-content-start col-12 p-0 mt-3 mt-lg-0&quot;]/div[@class=&quot;col-lg-12 col-6 pl-0 col-xl-3&quot;]/div[@class=&quot;m-textField mdc-text-field mdc-text-field--outlined mdc-text-field--valid&quot;]/input[@id=&quot;cvv&quot;]</value>
      <webElementGuid>2b16e2ce-3803-4d34-a872-770314533ee3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cvv']</value>
      <webElementGuid>672b29ec-b860-42f9-98ee-30903252a328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='case1']/div/div/div[2]/div/input</value>
      <webElementGuid>d7cef601-5a71-46ce-9369-bf5ebede599a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>0e932a3b-dc7e-4538-876c-aea01b22cb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cvv' and @type = 'password' and (text() = 'Código de seguridad' or . = 'Código de seguridad') and @name = 'cvv']</value>
      <webElementGuid>d598cd3a-8a78-4ae4-b805-73772ab03476</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
