<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Eliminar_opc</name>
   <tag></tag>
   <elementGuidId>500dd616-2615-4bbe-a636-b8e2449e44d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@class='a-btn-myBag--elements a-btn--elementsMyBags a_myBag__btnElements--desktop'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1022e1fe-ee20-4c5b-a26f-7bb8e32f483c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn-myBag--elements a-btn--elementsMyBags a_myBag__btnElements--desktop</value>
      <webElementGuid>ae8a37d1-9cbe-4ad2-86b2-f540bccd4a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eliminar</value>
      <webElementGuid>b7b3ab57-c17c-4488-9619-d3b9c537eb01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_productsContainer&quot;)/div[@class=&quot;col-12 m-box m-box-adjust m-checkout__productAdded pt-3&quot;]/div[@class=&quot;product-card-container&quot;]/div[@class=&quot;m-latestinlineElement m-latestinlineElement--triple mt-3 pl-lg-0 product-remove&quot;]/button[@class=&quot;a-btn-myBag--elements a-btn--elementsMyBags a_myBag__btnElements--desktop&quot;]</value>
      <webElementGuid>9497f0fb-db54-4f35-b1c5-e99b0ef0f981</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_productsContainer']/div/div[2]/div[11]/button[3]</value>
      <webElementGuid>bc4dc4cb-2d5d-4811-a455-971d8fde5d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mover a Wishlist'])[2]/following::button[1]</value>
      <webElementGuid>ec2fc17d-196d-46c6-b88b-63ca8ae68976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprar para mesa de regalos'])[2]/following::button[2]</value>
      <webElementGuid>1b4d4642-a0c9-4408-b5cd-de82f85f65cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resumen de compra'])[1]/preceding::button[1]</value>
      <webElementGuid>4599ba84-e5f8-40a6-957a-8789ca642a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cupones'])[1]/preceding::button[1]</value>
      <webElementGuid>6241602c-a19a-4d05-b886-b171b4720ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>997a6bbc-4da9-4b13-943f-c125f954e40a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Eliminar' or . = 'Eliminar')]</value>
      <webElementGuid>23cc81b7-bb6b-4080-af4a-aea9222cdfa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
