<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continuar_payment_opc</name>
   <tag></tag>
   <elementGuidId>2ef51554-5c56-46c4-a2c9-45d978eb6c04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.a-btn.a-btn--primary.333</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='opc_deliveryPayModalButtons']/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>53432be1-2c93-4a4a-8013-ffe15c2ad9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--primary 333</value>
      <webElementGuid>f98b7687-5aff-473a-96e6-dbcbe95c573a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>41fa862c-7924-404e-8b1e-a8c3cfd719f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_deliveryPayModalButtons&quot;)/div[@class=&quot;opc_continuarModal isAndroid&quot;]/button[@class=&quot;a-btn a-btn--primary 333&quot;]</value>
      <webElementGuid>0abf5997-beb4-4904-944f-5a684eb6ee25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_deliveryPayModalButtons']/div/button</value>
      <webElementGuid>182354e7-88c3-448b-846a-77aa5672707e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Esta solicitud de pedido es válida únicamente antes del 27 Feb 2023/23:59:59.'])[1]/following::button[1]</value>
      <webElementGuid>2d3c7ac6-12cd-4a0c-b414-7e8276cea565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IMPORTANTE:'])[2]/following::button[1]</value>
      <webElementGuid>2d871c5a-5d73-499a-9329-e9eb1a1385d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirma tu compra'])[1]/preceding::button[1]</value>
      <webElementGuid>bdb82218-deed-4c9c-86b2-7b98a274b17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continuar']/parent::*</value>
      <webElementGuid>5f9b1ec0-2979-4fd6-8d50-f40c547528a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>a8a9490a-dcb0-4fa7-8bde-e597d43e92ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Continuar' or . = 'Continuar')]</value>
      <webElementGuid>cb354572-cca7-4959-b96c-727ede6c2a59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
