<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cupones_opc</name>
   <tag></tag>
   <elementGuidId>c21bdff0-41b8-4e32-b29e-a7d18fa152e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='opc_buysummary']/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.a-btn.a-btn--onePageCheckout--deliveryAddress.d-inline.breakdown-expenses__coupons_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb573356-7758-4d7f-ba94-0f96e538d8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--onePageCheckout--deliveryAddress d-inline breakdown-expenses__coupons_button</value>
      <webElementGuid>c2052a3e-ec62-4d00-9d7e-366ef12a7f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cupones</value>
      <webElementGuid>0cb2e304-0439-4e63-8b46-de06b4fd4b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_buysummary&quot;)/div[@class=&quot;m-breakdownExpense breakdown-expenses__coupons&quot;]/button[@class=&quot;a-btn a-btn--onePageCheckout--deliveryAddress d-inline breakdown-expenses__coupons_button&quot;]</value>
      <webElementGuid>de885198-a10d-4a22-943d-3f7be35f433c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_buysummary']/div/button</value>
      <webElementGuid>2163c698-b761-4181-aded-032da3ed8727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resumen de compra'])[1]/following::button[1]</value>
      <webElementGuid>af885902-1aee-4f7b-a81e-8175d04c0ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar'])[2]/following::button[1]</value>
      <webElementGuid>51ab77bd-47bd-45d9-b574-0c7092aa6e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirma tu compra'])[2]/preceding::button[1]</value>
      <webElementGuid>7774abd4-673d-47f5-b10e-30e971836cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>cb8747d6-74da-47e6-a376-39eb60892ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Cupones' or . = 'Cupones')]</value>
      <webElementGuid>47fc468a-6b76-4136-a583-d591e1bc8c10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
