<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>city_addAddress_opc</name>
   <tag></tag>
   <elementGuidId>97df3e62-50fe-4b26-9afd-90a19106241f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='city']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;city&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1a2977e-853e-41ee-9bdd-9d8e0939905e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-textField__input mdc-text-field__input</value>
      <webElementGuid>88f23edb-5b50-4892-ad43-566d02d343b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4654833-0557-47ae-9f1d-2615e5074b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>618fbd2e-8514-4278-aceb-bc809732cd97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>helper-nombreCorto</value>
      <webElementGuid>445dc382-a5e4-4f1d-a859-953665359b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>helper-nombreCorto</value>
      <webElementGuid>6a5a3b10-d349-4077-ba97-452f51886f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>50d13bb6-f1eb-4c22-b917-292add544aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ej. Casa, Oficina...</value>
      <webElementGuid>005d9537-c108-4eb7-a6cf-5df86630355f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>textWithSpecialChars</value>
      <webElementGuid>821677a3-4c4c-4734-adb9-5dd5ed106a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>21c8f585-2872-46bb-ad2f-ccad6c7ac6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>reference</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>9a15eb0d-bade-4c94-a0c2-9ec83f863d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputid</name>
      <type>Main</type>
      <value>nombreCorto</value>
      <webElementGuid>9736c515-51b2-40d1-a776-874dacae8200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nameinput</name>
      <type>Main</type>
      <value>nombreCorto</value>
      <webElementGuid>4816db92-39e5-4184-9055-c32dad846936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelposition</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>627c8ee1-2205-492c-b4e6-46600551ad07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpertextid</name>
      <type>Main</type>
      <value>helper-nombreCorto</value>
      <webElementGuid>a0707054-7d83-41a4-82cb-31456822048f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labeltext</name>
      <type>Main</type>
      <value>Ciudad:</value>
      <webElementGuid>cd0176b7-357b-4234-af80-2a0aa6a89997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_modalAddNewShipAddress&quot;)/form[1]/div[@class=&quot;row align-items-start&quot;]/div[@class=&quot;col-xl-3 col-lg-3 col-12&quot;]/div[@class=&quot;m-textField mdc-text-field mdc-text-field--outlined mdc-text-field--focused mdc-text-field--invalid falsefalse&quot;]/input[@class=&quot;a-textField__input mdc-text-field__input&quot;]</value>
      <webElementGuid>6a16b6d7-f041-4489-b202-fa214d5288fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='city']</value>
      <webElementGuid>b821223a-649b-42e5-be16-15277da8119e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_modalAddNewShipAddress']/form/div[4]/div[5]/div/input</value>
      <webElementGuid>96a368fd-8a7a-40e1-81f7-c49fe8f24bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>2b2833e2-b58e-4b04-8144-a2543ab719ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'city' and (text() = 'Ej. Casa, Oficina...' or . = 'Ej. Casa, Oficina...')]</value>
      <webElementGuid>d74d4d0e-fb76-4ea4-bdfd-fd20177443f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
