<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Cambiar_payment_opc</name>
   <tag></tag>
   <elementGuidId>0798494b-8a25-42fd-8f93-46beb007a674</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='opc_PayMethod_background']//div[@class='a-box__accordionIcon float-right']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.text-shutdown-card.cambiarLabelTxt.text-size-card</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>758e607e-f1c4-4f88-9871-a236a5d3a47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-shutdown-card cambiarLabelTxt text-size-card</value>
      <webElementGuid>88f21b0c-db4a-45db-bc18-a25e2fd42494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cambiar</value>
      <webElementGuid>12119a57-2fb7-4e5b-8720-5900cca8cd22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_section-PayMethod&quot;)/div[@class=&quot;d-flex flex-row align-items-start justify-content-start pt-1 pl-2 pr-1&quot;]/div[@class=&quot;w-100&quot;]/button[@class=&quot;a-btn a-btn--onePageCheckout--deliveryAddress d-inline&quot;]/div[@class=&quot;a-box__accordionIcon float-right&quot;]/label[@class=&quot;text-shutdown-card cambiarLabelTxt text-size-card&quot;]</value>
      <webElementGuid>f3b72246-7053-41ea-886b-f703a317dd18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_section-PayMethod']/div/div[2]/button/div/label</value>
      <webElementGuid>18f8a5d1-c692-419b-aad3-bd6bc9bd0a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*9488'])[1]/following::label[1]</value>
      <webElementGuid>30c0939f-4ff5-45e6-b236-80518cddb67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MM/AA'])[1]/preceding::label[1]</value>
      <webElementGuid>ddb2610d-0dea-4939-aab3-30a8c32400f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CVV'])[1]/preceding::label[2]</value>
      <webElementGuid>40ea9edc-700d-42c0-87b0-20f2733a7d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/div/label</value>
      <webElementGuid>c0e41d1b-e0ce-4117-9f1d-c33f62d7171c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Cambiar' or . = 'Cambiar')]</value>
      <webElementGuid>c7d51076-a8b4-42c2-a259-1c7213e722da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
