<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LADA_addAddress_opc</name>
   <tag></tag>
   <elementGuidId>20464633-986f-400e-9dd6-10d15aad4a67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='LADA']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;LADA&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcac5d27-74b4-4ec7-a9ff-dfd1146c8759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-textField__input mdc-text-field__input</value>
      <webElementGuid>143b75fe-3337-4ccc-a0f2-e5a235e912ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>f2e963bb-5290-4cc2-abe2-b2e0b8ae0618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>643061d8-afda-422f-bb7c-cc21afffaa53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>helper-nombreCorto</value>
      <webElementGuid>335870ee-332b-4916-bc6c-d0bca3e30086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>helper-nombreCorto</value>
      <webElementGuid>ecea3d08-ad9b-4e3d-9dbe-eb7af4d9671a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LADA</value>
      <webElementGuid>051a52ac-c006-446d-922f-e43b8a8a833a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0466dd2d-3462-4489-9e4b-5f37c00e1b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>onlyNumbersWithMaxLength</value>
      <webElementGuid>8b047b78-0130-431e-b2ab-883281203fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>ddaef205-63d2-4b94-9722-5cb78590b548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>reference</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>5eae220a-3c53-489d-8ab1-d56dfa6f4a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labeltext</name>
      <type>Main</type>
      <value>LADA</value>
      <webElementGuid>4ff11414-e4f2-497e-a258-954ebce92269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_modalAddNewShipAddress&quot;)/form[1]/div[@class=&quot;row align-items-start&quot;]/div[@class=&quot;col-xl-3 col-lg-3 col-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-6&quot;]/div[@class=&quot;m-textField mdc-text-field mdc-text-field--outlined mdc-text-field--valid&quot;]/input[@class=&quot;a-textField__input mdc-text-field__input&quot;]</value>
      <webElementGuid>67515dee-4233-4b30-b9e9-420ed96b35fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='LADA']</value>
      <webElementGuid>98aef140-2127-4edb-bc8e-0569dd25bef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_modalAddNewShipAddress']/form/div[4]/div[14]/div/div/div/input</value>
      <webElementGuid>fcd4eea1-53ce-4cd3-b915-0cf852450c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div/input</value>
      <webElementGuid>ecce1ffb-31f0-434d-8c42-e1cb52d252ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'LADA' and (text() = 'text' or . = 'text')]</value>
      <webElementGuid>8de15d1b-e043-4029-9ab5-e91605f421ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
