<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mothersLastName_addAddress_opc</name>
   <tag></tag>
   <elementGuidId>7f3a6c47-1e0f-40db-b0f3-02e0eeb78368</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='mothersLastName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;mothersLastName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3e16233-d119-4107-b68b-e6eb6a40ec60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-textField__input mdc-text-field__input</value>
      <webElementGuid>67d09756-6265-4aac-81aa-959dc8a887e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fed554c6-5256-4af7-b8ed-25c2ed384e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6323fdbd-3ba7-4071-90a4-62c72c583770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>helper-nombreCorto</value>
      <webElementGuid>9aebfa13-4b31-46cb-93e6-9cd243ffba52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>helper-nombreCorto</value>
      <webElementGuid>803186f7-c64e-49b2-8d7a-32790a36eb48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mothersLastName</value>
      <webElementGuid>4f0dd493-f5d7-415d-a060-54e8663b35ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ej. Casa, Oficina...</value>
      <webElementGuid>10f0c90d-ff51-44fb-99f8-7301e513b511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>textWithSpecialChars</value>
      <webElementGuid>838c26df-6d2c-4c33-b635-66f40f74d820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>57c8210d-13d3-49a0-9f5e-789d2b02b2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>reference</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>2635df46-e024-4cdf-9bf5-bdddab4858f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputid</name>
      <type>Main</type>
      <value>nombreCorto</value>
      <webElementGuid>8bd414ab-4acb-4edd-a145-64d82c98ca76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nameinput</name>
      <type>Main</type>
      <value>nombreCorto</value>
      <webElementGuid>e1e413e9-ec2f-4dfb-90e9-8e08fd3ffe71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelposition</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>7b326b09-88bc-4a1c-9729-904e934a16e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helpertextid</name>
      <type>Main</type>
      <value>helper-nombreCorto</value>
      <webElementGuid>addc66d9-f43f-4c09-99a0-d8a790ffa030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labeltext</name>
      <type>Main</type>
      <value>Apellido Materno</value>
      <webElementGuid>884f6937-848a-4f8b-8c08-651da9cf1446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Test</value>
      <webElementGuid>cdac786e-f470-42fe-acdf-de01c2aa95ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_modalAddNewShipAddress&quot;)/form[1]/div[@class=&quot;row align-items-start&quot;]/div[@class=&quot;col-xl-3 col-lg-3 col-12&quot;]/div[@class=&quot;m-textField mdc-text-field mdc-text-field--outlined mdc-text-field--valid&quot;]/input[@class=&quot;a-textField__input mdc-text-field__input&quot;]</value>
      <webElementGuid>f0d26f1e-e902-4687-b52b-de44cfed1005</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='mothersLastName']</value>
      <webElementGuid>a107cce9-bf40-4c01-90be-121894a202d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_modalAddNewShipAddress']/form/div[2]/div[3]/div/input</value>
      <webElementGuid>3af658b9-f598-42c9-addc-f07e5c77d8dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>978e95d6-d5f0-4388-a469-ee74d124b22b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'mothersLastName' and (text() = 'Ej. Casa, Oficina...' or . = 'Ej. Casa, Oficina...')]</value>
      <webElementGuid>cf98002d-9743-47ef-af1e-19d08e474747</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
