<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>productImage_opc</name>
   <tag></tag>
   <elementGuidId>742f5fef-09aa-48c5-92e0-3d6836b8c12c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='opc_productsContainer']/div/div[2]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.a-checkout__imageProduct</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d55bd050-fc33-45fa-9eaa-842d6c08960e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss237.liverpool.com.mx/lg/1111964187.jpg</value>
      <webElementGuid>aecb35c7-4261-485a-a8b1-f6e2f911bd43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>product</value>
      <webElementGuid>54259fbd-1600-4238-9ec7-7e1a5a675796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-checkout__imageProduct</value>
      <webElementGuid>902c72c8-0b87-492e-9f66-ab159bf6a617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_productsContainer&quot;)/div[@class=&quot;col-12 m-box m-box-adjust m-checkout__productAdded pt-3&quot;]/div[@class=&quot;product-card-container&quot;]/div[@class=&quot;p-1 product-image&quot;]/img[@class=&quot;a-checkout__imageProduct&quot;]</value>
      <webElementGuid>1a02e920-f086-4bb5-bd43-a262cb116a50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_productsContainer']/div/div[2]/div/img</value>
      <webElementGuid>e824d585-c511-41af-9e12-2b894c04d2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='product']</value>
      <webElementGuid>6260bab4-5c9d-4fab-bff6-a6210965b737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>1afe9526-4015-4fe7-9dde-7bb104245fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ss237.liverpool.com.mx/lg/1111964187.jpg' and @alt = 'product']</value>
      <webElementGuid>bb4bf15c-918b-4a49-bf14-69ea2575cc45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
