<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Annimo</name>
   <tag></tag>
   <elementGuidId>5e3f7da9-2dbe-414e-867a-6d434df022b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navContext_customerNavItem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navContext_customerNavItem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>687bbd74-e2da-4ba7-a966-d06c91950f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>3aa3b7c3-ed98-4c41-b095-8537f021a5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navContext_customerNavItem</value>
      <webElementGuid>4f81768e-b9c2-4a56-afe9-91611783f71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>viewCurrentCustomer('customersTab');</value>
      <webElementGuid>469dd617-6b76-4020-939e-17912175cd7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gcn_btn_context</value>
      <webElementGuid>0bed5aeb-d8f6-4eb0-9639-7c6e71107603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ver información de cliente</value>
      <webElementGuid>f51d17c2-61cd-43fb-9825-a3f8ec0fd97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anónimo</value>
      <webElementGuid>a25d1ab5-8db6-419e-86b7-b59f6b527103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navContext_customerNavItem&quot;)</value>
      <webElementGuid>ac7ba400-e0e3-4f55-b756-71cc7db29859</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='navContext_customerNavItem']</value>
      <webElementGuid>9201d69e-b3fa-4041-82d5-c58b33e50832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navItem_customerNavItem']/div/div/a[2]</value>
      <webElementGuid>973ebded-5a78-4b80-8f8e-1a93579a34f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Anónimo')]</value>
      <webElementGuid>592a88d4-a451-4655-9293-f6f1483a65b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar cliente'])[1]/following::a[1]</value>
      <webElementGuid>448d59a9-884e-4805-9602-11c9492af812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista de precios'])[1]/following::a[4]</value>
      <webElementGuid>cc9432e2-6ad5-4e8e-a225-482ee0ec922f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cliente'])[1]/preceding::a[2]</value>
      <webElementGuid>9bd9567b-c0e8-4065-a4bc-4b37fb8ce296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar órdenes'])[1]/preceding::a[6]</value>
      <webElementGuid>f21cf788-e3a2-4f41-bf5a-757ea187945d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Anónimo']/parent::*</value>
      <webElementGuid>b3128651-25cf-454a-8e8c-886fb2c93376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[29]</value>
      <webElementGuid>bd074325-6227-4d6e-ab68-ef13a270bb8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a[2]</value>
      <webElementGuid>9beecbdd-17a1-4450-ab03-9e1dd5d0ca7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'navContext_customerNavItem' and @title = 'Ver información de cliente' and (text() = 'Anónimo' or . = 'Anónimo')]</value>
      <webElementGuid>31950837-a8d9-41ea-b7e9-a95188b4fa87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
