<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Comparador_icon-search</name>
   <tag></tag>
   <elementGuidId>223ff9b1-c89f-4702-bc4a-276814bd34f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.icon-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='icon-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>de3bf101-3bfc-477b-92a3-0b371d8bc8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-search</value>
      <webElementGuid>ba1c8515-3eaf-46f0-a601-d53a1dfdd29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>searchTermInputOnkeydown(); submitSearchTermRequest('/agent/framework.jsp?_windowid=32&amp;ps=cmcCatalogPS&amp;p=cmcProductCatalogSearchP');</value>
      <webElementGuid>0cc126d6-6d82-4d32-abdb-067b538037e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;catalog-nav&quot;)/div[@class=&quot;search&quot;]/ul[1]/li[@class=&quot;search-row&quot;]/div[@class=&quot;icon-search&quot;]</value>
      <webElementGuid>486ebffb-6c51-486c-9892-70b77b27a4e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick=&quot;searchTermInputOnkeydown(); submitSearchTermRequest('/agent/framework.jsp?_windowid=32&amp;ps=cmcCatalogPS&amp;p=cmcProductCatalogSearchP');&quot;]</value>
      <webElementGuid>c05e91bb-f74b-4787-aab9-48564b21373e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='catalog-nav']/div/ul/li/div</value>
      <webElementGuid>0df0b795-6115-4df3-8b35-502bb2b1bf39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div</value>
      <webElementGuid>4b980840-0039-4424-93cd-8443c5713100</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
