<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1</name>
   <tag></tag>
   <elementGuidId>f82817f8-a7b2-4e17-a7a5-8ff09bf85645</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navActionContainer_siteNavItem > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navActionContainer_siteNavItem']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3af98071-ac09-4828-b0b4-c42e2e320d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navActionContainer_siteNavItem&quot;)/div[1]</value>
      <webElementGuid>288021ce-e2ac-4f31-b1c2-cc2de4e377ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='navActionContainer_siteNavItem']/div</value>
      <webElementGuid>56447f5a-cff2-483d-8426-f1fbdc9ec6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar sitio'])[1]/following::div[1]</value>
      <webElementGuid>fe527dbc-3453-4f73-a426-9c29e1de7b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shun Shun es ahora el cliente activo.'])[2]/following::div[5]</value>
      <webElementGuid>def044cc-53e1-493a-bded-855df59fca0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sitio'])[1]/preceding::div[1]</value>
      <webElementGuid>d79891a6-04de-43db-9c63-fcccebf635a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar catálogo'])[1]/preceding::div[3]</value>
      <webElementGuid>74092b1f-d451-4d66-8be8-10edd71b4e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/div</value>
      <webElementGuid>d2df578b-ae55-45ff-a20d-a76529379fc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
