<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Precio total_atg_commerce_csr_catalog_b4aff5</name>
   <tag></tag>
   <elementGuidId>eba531c0-df71-4c1b-ad1c-c95da39db1b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#atg_commerce_csr_catalog_productId1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='atg_commerce_csr_catalog_productId1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5cff96b-cff3-4ddc-8314-81cdb5420f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b6b1b4e-e805-4e25-9e21-8051cd3d689f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>atg_commerce_csr_catalog_productId1</value>
      <webElementGuid>8c024efc-da10-4504-a6a2-c29566127a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>atg_commerce_csr_catalog_productId1</value>
      <webElementGuid>455c0554-43a6-4155-8b5e-5443d67f66a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>1c96ca13-e9ea-4ca8-9d84-d6cc8420692c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;atg_commerce_csr_catalog_productId1&quot;)</value>
      <webElementGuid>39785a57-64dd-4116-9dbd-c0bd7f8d4889</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='atg_commerce_csr_catalog_productId1']</value>
      <webElementGuid>18922465-d6c9-43a8-9a3f-2fe6c895f09a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='productCell1']/input</value>
      <webElementGuid>3b893f1b-5be0-45df-b7fc-f140bb71131b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>8e2da484-50bb-4fd7-8926-7028979cb0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'atg_commerce_csr_catalog_productId1' and @name = 'atg_commerce_csr_catalog_productId1']</value>
      <webElementGuid>56f681be-a12a-4008-8a4e-661d5401baa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
