<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__cpFirstName</name>
   <tag></tag>
   <elementGuidId>1652f66a-8c64-4991-a8e6-17ef28036a13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cpFirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cpFirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b365f53d-f6a4-4733-910e-6e1172c64151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dojoattachpoint</name>
      <type>Main</type>
      <value>textbox,focusNode</value>
      <webElementGuid>c7be39f9-d64e-489e-8675-3cd575a4625c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dojoattachevent</name>
      <type>Main</type>
      <value>onfocus,onblur:_onMouse,onkeyup,onkeypress:_onKeyPress</value>
      <webElementGuid>6e6142d2-beb1-4361-bea3-6826f940ac7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>83892b7d-ce4a-4d44-8808-3053ee915aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>34b33443-b72b-4d9d-9230-4294a7da01e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cpFirstName</value>
      <webElementGuid>9f948de6-d3d3-4e2f-896e-5599380db549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cpFirstName</value>
      <webElementGuid>35fcbf65-bb9f-44be-864d-ccb9a4b6aa36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f7dc748b-fda8-4a3a-93e3-e0650ffd6acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>f2998164-db11-41d3-b24b-524cc7c12a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>277282ed-2f16-4abd-8b6a-ebe97471b5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7ff02c9a-5b3a-4ce3-975f-a85a2a2145a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>  atg-base-table-customer-create-input profilenew-fragmentinput</value>
      <webElementGuid>ec603272-6536-4c32-b7b5-1e20797ef161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpFirstName&quot;)</value>
      <webElementGuid>76417a57-b5fc-4dfe-99fc-d98cebf6af2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cpFirstName']</value>
      <webElementGuid>2704469a-fe7f-467d-8dad-dfa03985e3aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='widget_cpFirstName']/tbody/tr/td/input</value>
      <webElementGuid>61a55ac7-bef2-4a05-b5c6-552a4f1e21cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>a27cd4f0-ac22-40d1-9056-75c44ff66fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cpFirstName' and @id = 'cpFirstName']</value>
      <webElementGuid>f50f5920-c5b3-4c43-be5c-a12782cf0758</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
