<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>e74926c5-3bba-46fd-bd49-b780485e4241</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navActionContainer_productNavItem > div > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navActionContainer_productNavItem']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4ebfb406-a5d3-4110-a57c-4b06f7dd3956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navActionContainer_productNavItem&quot;)/div[1]/span[1]</value>
      <webElementGuid>bd8f34e6-e446-41ea-8569-d4fe1028a8c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='navActionContainer_productNavItem']/div/span</value>
      <webElementGuid>5d3ee466-19ed-4fcb-a806-c41f5a91eaef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/span</value>
      <webElementGuid>a24f794e-4ebd-458b-a509-1c3e6841671b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
