<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TotalPrice_opc</name>
   <tag></tag>
   <elementGuidId>71e3524d-3c6b-49ea-ac42-910915f8d5e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='m-breakdownExpenses__column--priceContainer']//p)[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.a-box__resume.-totalPrice</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>504a6ac7-fede-4cef-9a0a-8f7f5e029838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-box__resume -totalPrice</value>
      <webElementGuid>37ca0051-3f6b-48d9-b27d-1ad872821eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$29.40</value>
      <webElementGuid>e1dc6db3-4387-4ee4-b813-a747074a3508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_buysummary&quot;)/div[@class=&quot;m-breakdownExpenses w-100 mt-0&quot;]/div[@class=&quot;m-breakdownExpenses__detail&quot;]/div[@class=&quot;m-breakdownExpenses__quantity&quot;]/div[@class=&quot;m-breakdownExpenses__column--priceContainer&quot;]/p[@class=&quot;a-box__resume -totalPrice&quot;]</value>
      <webElementGuid>b10ef042-6c4a-4849-86f5-a64482418e61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_buysummary']/div[2]/div[2]/div[2]/div/p</value>
      <webElementGuid>8fc28848-a5c8-41bd-b7df-12fe1a0430da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(2 disponibles)'])[1]/following::p[10]</value>
      <webElementGuid>afbf6470-1175-4bc4-b2f2-e27ae6a966f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cupones'])[1]/following::p[10]</value>
      <webElementGuid>3f6287ba-0437-49c3-a00a-860bbd582830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirma tu compra'])[2]/preceding::p[2]</value>
      <webElementGuid>4ea66796-6448-423b-a078-4b709e1bfe56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total:'])[1]/preceding::p[2]</value>
      <webElementGuid>f8ad4e23-7243-4f93-bdb0-594f7444f92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]/div/p</value>
      <webElementGuid>f14eeeba-c8dd-4dda-9aa0-1755a5740a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '$29.40' or . = '$29.40')]</value>
      <webElementGuid>48b8abd4-2386-4983-b733-cfb5f35a216d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
