<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Buscar(SearchProduct)_NavItem_LP</name>
   <tag></tag>
   <elementGuidId>107370f6-736a-468c-abce-34f8db63e18d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navSearch_productNavItem > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navSearch_productNavItem']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a0fc86cf-016d-464a-9aaa-b03d11d9d539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buscar en catálogo</value>
      <webElementGuid>7c3d5aea-1ad5-44cf-98f1-3523dcdf1737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navSearch_productNavItem&quot;)/span[1]</value>
      <webElementGuid>1c2cf811-4205-453b-b722-e1a5cd486b13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='navSearch_productNavItem']/span</value>
      <webElementGuid>304fe5c3-e577-4b19-afa6-38a2de79bf34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orden'])[1]/following::span[1]</value>
      <webElementGuid>cfeea413-3112-4852-ac7c-e039d718a9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar órdenes'])[1]/following::span[2]</value>
      <webElementGuid>e299a6c3-8365-413f-9ae3-7e747dd510f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Productos'])[1]/preceding::span[1]</value>
      <webElementGuid>6733b991-2f37-4dea-bba0-53d84cfd0b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar caso'])[1]/preceding::span[2]</value>
      <webElementGuid>585b4682-669d-4501-9693-ef1c2c5dc0d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buscar en catálogo']/parent::*</value>
      <webElementGuid>af303dbe-beef-43ed-8aac-5e105df29c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div/a/span</value>
      <webElementGuid>8abf4be0-be81-4f75-b110-f13996f8b648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Buscar en catálogo' or . = 'Buscar en catálogo')]</value>
      <webElementGuid>0b8dde9b-3078-4f5c-ba38-129527b3f367</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
