<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Customer_searchButton_LP</name>
   <tag></tag>
   <elementGuidId>95905967-5599-4060-a88b-abbd5b21b657</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21eff5c5-dbfb-48e9-a74d-23258c3e19ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f9844108-3ce3-4f37-89b3-87b707ff6e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>cce4f67f-f9ba-43dd-8c30-5993456ae330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchButton</value>
      <webElementGuid>67792f35-d375-4a36-b8de-b5f1bed3b793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchButton</value>
      <webElementGuid>c1551344-ac6b-4f3b-b059-d3cceb6731cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>dojo.byId('atg_service_customer_searchPageNum').value = '0'; this.disabled=true;atg.service.customer.search.profileSearch();return false;</value>
      <webElementGuid>1e2e972d-a64e-47b0-9c3b-118a1dcdf59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;atg_service_customer_searchForm&quot;)/div[@class=&quot;atg-csc-base-table&quot;]/div[@class=&quot;atg-csc-base-table-row&quot;]/div[@class=&quot;atg_svc_panelFooter atg-csc-base-table-cell&quot;]/input[@id=&quot;searchButton&quot;]</value>
      <webElementGuid>1df56c2d-056b-4612-9da8-2743833fd374</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchButton']</value>
      <webElementGuid>54e50e06-9260-4e55-9218-f2f2d56e3e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='atg_service_customer_searchForm']/div[3]/div[4]/div[6]/input</value>
      <webElementGuid>08b6d627-7ff8-46b8-b061-faac6e135eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>110774fc-799e-4923-80b9-c15e579960be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'searchButton' and @id = 'searchButton']</value>
      <webElementGuid>373e0657-4e1d-4aa0-9257-8fe711853b2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
