<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CustomerOption1_LP</name>
   <tag></tag>
   <elementGuidId>97c7e1db-fb77-4cb9-98af-6e80ee12db6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2) > #atg_commerce_csr_customer_viewMoreCustomerInfotheCustomerId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='atg_commerce_csr_customer_viewMoreCustomerInfotheCustomerId'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>36987c25-b911-4c3a-85cb-c7d97dad5a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>dec42338-9f56-4128-84f9-26b7714f37cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blueU</value>
      <webElementGuid>4a749419-7762-45cd-a31b-fc9ae09ea75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ver cliente</value>
      <webElementGuid>43114f83-3a0f-4d0a-9ba4-e53b549a8e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>viewCustomerFromSearch('1715010038');</value>
      <webElementGuid>27437be2-4787-4934-bad1-96b96e06c4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>atg_commerce_csr_customer_viewMoreCustomerInfotheCustomerId</value>
      <webElementGuid>cb7fbdd9-f0ab-44e7-9fb5-fce074e856b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shun@222.com</value>
      <webElementGuid>05750611-b485-4a77-b7ef-71e64ad4357d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customerSearchResultsPanelContent&quot;)/div[@class=&quot;atg_commerce_csr_content&quot;]/table[@class=&quot;atg_dataTable&quot;]/tbody[1]/tr[1]/td[2]/a[@id=&quot;atg_commerce_csr_customer_viewMoreCustomerInfotheCustomerId&quot;]</value>
      <webElementGuid>887f031d-f8dc-4c8c-b6a2-8c25a0260b60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='atg_commerce_csr_customer_viewMoreCustomerInfotheCustomerId'])[2]</value>
      <webElementGuid>72754bfc-f30f-4479-aaca-880142256d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customerSearchResultsPanelContent']/div/table/tbody/tr/td[2]/a</value>
      <webElementGuid>6670dc8b-c927-4d9a-8cbf-a50f2f26822f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Shun@222.com')]</value>
      <webElementGuid>3e5d74fe-2b12-4a36-991d-7879b2ce61f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No hay órdenes para este cliente.'])[1]/following::a[1]</value>
      <webElementGuid>99065771-5079-4f13-96d3-5f842f3616f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado'])[2]/following::a[1]</value>
      <webElementGuid>d41d8f4a-3f04-41de-a578-7ff45eb88572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shun'])[1]/preceding::a[1]</value>
      <webElementGuid>e837d955-b1a6-46a4-aaf5-061b5c95caf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shun'])[2]/preceding::a[1]</value>
      <webElementGuid>84e839e4-953d-4adc-b710-dee308519690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shun@222.com']/parent::*</value>
      <webElementGuid>68ca4d21-499e-41bc-9de9-66d6c649a107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[72]</value>
      <webElementGuid>928ea16e-8e37-4d03-8eea-301bb55c59ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>c3b09bfd-5791-45f4-a35d-8ccfcafd02ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Ver cliente' and @id = 'atg_commerce_csr_customer_viewMoreCustomerInfotheCustomerId' and (text() = 'Shun@222.com' or . = 'Shun@222.com')]</value>
      <webElementGuid>3a7c322a-b458-4ee4-a8e5-ea9cd345391d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
