<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nombre_SearchByFirstName_LP</name>
   <tag></tag>
   <elementGuidId>4bf784a5-7a7d-4361-90cd-984e6538135f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#atg_service_customer_searchFirstNameValue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='atg_service_customer_searchFirstNameValue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12847e7b-9165-4d86-8925-5b332f91de32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>71a9d1ae-0fb0-4886-9845-753877b666d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>d5addf85-773f-4dd1-91f8-40a8d76e7fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>/atg/svc/agent/ui/formhandlers/CustomerSearchTreeQueryFormHandler.searchRequest.fields[0].value</value>
      <webElementGuid>8866a4a2-5092-4c50-8263-a079304ddf88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>atg_service_customer_searchFirstNameValue</value>
      <webElementGuid>316df1e6-3608-44df-a5d1-0e8c41049c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e93b815-f8f9-414b-aea3-0b1957b24cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>atg-base-table-customer-search-input table_textbox</value>
      <webElementGuid>997f1aa3-8abe-43b7-8b85-5f833e84a6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;atg_service_customer_searchFirstNameValue&quot;)</value>
      <webElementGuid>fee351b9-2783-445c-b46d-a3cd9bb7931a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='atg_service_customer_searchFirstNameValue']</value>
      <webElementGuid>5191e9c0-8e83-477e-b903-64455a6098fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='atg_service_customer_searchForm']/div[3]/div/span/input</value>
      <webElementGuid>6bca06bd-67a3-4b4e-9fec-93ae3288efd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/input</value>
      <webElementGuid>860e1e5d-ddfb-45e9-a3d0-c172bfce3977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '/atg/svc/agent/ui/formhandlers/CustomerSearchTreeQueryFormHandler.searchRequest.fields[0].value' and @id = 'atg_service_customer_searchFirstNameValue' and @type = 'text']</value>
      <webElementGuid>ca210d93-f832-4c75-8695-3bb5ebba2155</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
